### ISSUE TITLE
About the problem of printing heatmap with lightweight openpose

### ISSUE THREAD

**Issue by EricerYang** [connernam/train#1]
Hi, brother. Sorry to interrupt you.
I see the question you mentioned in lightweight openpose where you print the heatmaps.
I follow your approach, use `tmp_img = images.squeeze().permute(1, 2, 0).detach().cpu().numpy()`
but i get `RuntimeError: number of dims don't match in permute`

After my debug:
I see that “images” are 4D, how do I transform 4D “images” into 3D?

I need you help my brother, I would be grateful.

**Comment by connernam** [comment]
Hi, @EricerYang 
Just change the batch size to 1.

**Comment by EricerYang** [comment]
> Hi, @EricerYang Just change the batch size to 1.

Thank you very much for your reply.
Following the practice you provided, my problem was solved. thank you very much！
